language: java

# whitelist
branches:
 only:
  - master
 
jdk:
 - oraclejdk8

# Run the commit message check and then check out some required dependencies.
# TODO Currently check in messages are not checked for dawnsci.
# - chmod +x ./org.eclipse.dawnsci.releng/build/commit-msg.sh
# - bash ./org.eclipse.dawnsci.releng/build/commit-msg.sh

before_install:
 - git clone --depth=50 --branch=master https://github.com/eclipse/richbeans.git ../org.eclipse.richbeans
 - git clone --depth=50 --branch=master https://github.com/DawnScience/dawn-third.git ../../dawn-third

# Run the build from org.eclipse.dawnsci
install:
  - cd ..
  - mv dawnsci org.eclipse.dawnsci
  - cd org.eclipse.dawnsci
 
# Maven compile and test 
# No need to run this as default travis will find maven and run it
# script: mvn clean compile surefire:test
